################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
OBJS := 
C++_DEPS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
pH \
pH/CMakeFiles/Ex1.dir \
pH/CMakeFiles/CompilerIdCXX \
pH/CMakeFiles/CompilerIdC \
Tools/Simulation/Ocean/uMVS \
Tools/Simulation/Ocean/uMVS/CMakeFiles/uMVS.dir \
Tools/Matlab/iMatlab \
Tools/Graphical/uPlayBack \
Tools/Graphical/uMS \
Tools/Graphical/uMS/CMakeFiles/uMS.dir \
Tools/Graphical/uIndexedPlayBack \
Tools/Graphical/libAlogTools/bin \
Tools/Graphical/libAlogTools/alogTools \
Tools/Console/uPoke \
Tools/Console/uPoke/CMakeFiles/uPoke.dir \
Thirdparty/newmat \
Thirdparty/newmat/CMakeFiles/newmat.dir \
Thirdparty/FLTKVW \
Thirdparty/FLTKVW/CMakeFiles/fltkvw.dir \
NavigationAndControl/pNav \
NavigationAndControl/pNav/CMakeFiles/pNav.dir \
NavigationAndControl/pHelm \
NavigationAndControl/pHelm/CMakeFiles/pHelm.dir \
NavigationAndControl/iRemote \
NavigationAndControl/iRemote/CMakeFiles/iRemote.dir \
NavigationAndControl/MOOSTaskLib \
NavigationAndControl/MOOSTaskLib/CMakeFiles/MOOSTask.dir \
NavigationAndControl/MOOSNavLib \
NavigationAndControl/MOOSNavLib/CMakeFiles/MOOSNav.dir \
Instruments/Ocean/iRelay \
Instruments/Ocean/iRelay/CMakeFiles/iRelay.dir \
Instruments/Ocean/iPH \
Instruments/Ocean/iPH/CMakeFiles/ipH.dir \
Instruments/Ocean/iPH/CMakeFiles/CompilerIdCXX \
Instruments/Ocean/iPH/CMakeFiles/CompilerIdC \
Instruments/Ocean/iLBL \
Instruments/Ocean/iLBL/CMakeFiles/iLBL.dir \
Instruments/Ocean/iJanitor \
Instruments/Ocean/iJanitor/CMakeFiles/iJanitor.dir \
Instruments/Ocean/iINS \
Instruments/Ocean/iINS/CMakeFiles/iINS.dir \
Instruments/Ocean/iDepth \
Instruments/Ocean/iDepth/CMakeFiles/iDepth.dir \
Instruments/Ocean/iDVL \
Instruments/Ocean/iDVL/CMakeFiles/iDVL.dir \
Instruments/Ocean/iCompass \
Instruments/Ocean/iCompass/CMakeFiles/iCompass.dir \
Instruments/Ocean/iBattery \
Instruments/Ocean/iActuation \
Instruments/Ocean/iActuation/CMakeFiles/iActuation.dir \
Instruments/Ocean/iADV \
Instruments/Common/iGPS \
Instruments/Common/iGPS/CMakeFiles/iGPS.dir \
Essentials/pScheduler \
Essentials/pScheduler/CMakeFiles/pScheduler.dir \
Essentials/pMOOSBridge \
Essentials/pMOOSBridge/CMakeFiles/pMOOSBridge.dir \
Essentials/pLogger \
Essentials/pLogger/CMakeFiles/pLogger.dir \
Essentials/pAntler \
Essentials/pAntler/CMakeFiles/pAntler.dir \
Essentials/MOOSUtilityLib \
Essentials/MOOSUtilityLib/CMakeFiles/MOOSUtility.dir \
Docs/ProgrammingWithMOOS/code/MOOSBinaryMessaging \
Docs/ProgrammingWithMOOS/code/MOOSBinaryMessaging/CMakeFiles/binary_comms_example.dir \
Docs/ProgrammingWithMOOS/code/Ex4 \
Docs/ProgrammingWithMOOS/code/Ex4/CMakeFiles/Ex4.dir \
Docs/ProgrammingWithMOOS/code/Ex3 \
Docs/ProgrammingWithMOOS/code/Ex3/CMakeFiles/Ex3.dir \
Docs/ProgrammingWithMOOS/code/Ex2 \
Docs/ProgrammingWithMOOS/code/Ex2/CMakeFiles/Ex2.dir \
Docs/ProgrammingWithMOOS/code/Ex1 \
Docs/ProgrammingWithMOOS/code/Ex1/CMakeFiles/Ex1.dir \
Docs/Essentials/Antler/code \
Docs/Essentials/Antler/code/CMakeFiles/pAntlerTestAppC.dir \
Docs/Essentials/Antler/code/CMakeFiles/pAntlerTestAppB.dir \
Docs/Essentials/Antler/code/CMakeFiles/pAntlerTestAppA.dir \
Core/MOOSLIB \
Core/MOOSLIB/CMakeFiles/MOOS.dir \
Core/MOOSGenLib \
Core/MOOSGenLib/CMakeFiles/MOOSGen.dir \
Core/MOOSDB \
Core/MOOSDB/CMakeFiles/MOOSDB.dir \
CMakeFiles/CompilerIdCXX \
CMakeFiles/CompilerIdC \

